#!/usr/bin/expect

set timeout 10
set host [lindex $argv 0]
set username [lindex $argv 1]
set password [lindex $argv 2]
set port [lindex $argv 3]

spawn ssh $username@$host -p $port
expect {
    ")?" {
        send "yes\n"
        expect "*assword:"
        send "$password\n"
    }
    "*assword:" {
        send "$password\n"
    }
    timeout {
        send \x03
        exit 1
    }
}

interact
exit
